apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana-app
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: grafana-app
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: grafana

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana
          imagePullPolicy: Never
          ports:
          - containerPort: 3000
            hostPort: 3000          
          livenessProbe:
            exec:
              command:
              - pgrep 
              - grafana
