apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: IFDB_NAME
          valueFrom:
            secretKeyRef:
              name: cluster-secret
              key: ifdb-name 
        - name: IFDB_USER
          valueFrom:
            secretKeyRef:
              name: cluster-secret
              key: ifdb-user 
        - name: IFDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cluster-secret
              key: ifdb-password
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - name: grafana-port
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: grafana

