apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: service_mysql
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
          name: sql-port
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        #livenessProbe:
        #  exec:
        #    command:
        #    - /bin/ash
        #    - -c
        #    - 'pgrep telegraf && pgrep mysqld'
        #  initialDelaySeconds: 10
        #  periodSeconds: 5
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-volume

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - name: sql-port
      protocol: TCP
      port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


