apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      restartPolicy: Always
      containers:
      - image: wordpress
        name: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: 5050
          initialDelaySeconds: 15
          timeoutSeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: wordpress
  ports:
  - port: 5050
    targetPort: 5050
    name: http
  type: LoadBalancer
  externalTrafficPolicy: Cluster
